// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgfoxnfwtfxnmwxqwvns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZm94bmZ3dGZ4bm13eHF3dm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDE3NzMsImV4cCI6MjA3ODAxNzc3M30.Bi4on7zEfGLpppvrUNd0VD78H0T_Moc_I9VxmDqXFFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});